# Generated by Django 3.1.2 on 2020-10-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('client_name', models.CharField(max_length=1000, verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Name')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone number')),
                ('age', models.DateField(blank=True, default=None, null=True, verbose_name='age')),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of last connection')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('experience_role', models.IntegerField(default=0, verbose_name='Senior')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date of Birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpleprojectmanagement.userprofile')),
            ],
            bases=('simpleprojectmanagement.userprofile',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpleprojectmanagement.userprofile')),
                ('specialisation', models.CharField(max_length=50, verbose_name='Specialisation')),
            ],
            bases=('simpleprojectmanagement.userprofile',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('time_elapsed', models.IntegerField(blank=True, default=None, null=True, verbose_name='Elapsed time')),
                ('importance', models.IntegerField(verbose_name='Importance')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hey', to='simpleprojectmanagement.userprofile', verbose_name='User')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleprojectmanagement.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='DevelopersOnTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_elapsed_dev', models.IntegerField(blank=True, default=None, null=True, verbose_name='Time elapsed')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleprojectmanagement.task')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleprojectmanagement.developer')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='developers',
            field=models.ManyToManyField(through='simpleprojectmanagement.DevelopersOnTask', to='simpleprojectmanagement.Developer'),
        ),
        migrations.AddField(
            model_name='developer',
            name='supervisedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heyme', to='simpleprojectmanagement.supervisor', verbose_name='Supervisor'),
        ),
    ]
